### ISSUE TITLE
Initializing MAX_MP3_BUFFER_SIZE causes compilation error in CircleCI

### ISSUE THREAD

**Issue by DominikWolek** [membraneframework/membrane-element-lame#14]
This lines in [`encoder.c`](https://github.com/membraneframework/membrane-element-lame/blob/new-testing-api/c_src/membrane_element_lame/encoder.c) won't compile:

```c
static const int SAMPLES_PER_FRAME = 1152;
// Magic numbers below taken from the worst case estimation in 'lame.h'
static const int MAX_MP3_BUFFER_SIZE = 5 * SAMPLES_PER_FRAME / 4 + 7200;
```

**Comment by mat-hek** [comment]
This probably happens because of an old version of gcc in the docker image
