### ISSUE TITLE
Avoid dependency on pkg-config

### ISSUE THREAD

**Issue by mspanc** [membraneframework/membrane-element-lame#18]
liblame on many platforms does not ship with pkg-config files by default, so bundlex is not able to determine its location while building the element.

Currently the outcome is usually:

```
==> membrane_element_lame
Bundlex: Building natives: encoder
Package lame was not found in the pkg-config search path.
Perhaps you should add the directory containing `lame.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lame' found
```

We need to invent a smarter way of handling that.

Workaround is to compile NIF you have to make sure ext/lame.pc is visible to the pkg-config. It is rather nasty hack.

**Comment by anildigital** [comment]
@mspanc Do you have steps to compile NIF for macOS? Thanks.

**Comment by mspanc** [comment]
More detailed workaround is explained here: https://github.com/membraneframework/membrane-element-shout/issues/4#issuecomment-533058286
